///////////////////////////////////////////////////////////
//  AccesoYVistaCraps.java
//  Implementation of the Class AccesoYVistaCraps
//  Generated by Enterprise Architect
//  Created on:      29-Jun-2008 07:45:35 p.m.
//  Original author: GIGA
///////////////////////////////////////////////////////////




using MVC.Vista;
namespace MVC.Controlador {
	public class AccesoYVistaCraps {

		private static AccesoYVistaCraps instancia;
		public AccesoYJuegoCraps m_AccesoYJuegoCraps;



		~AccesoYVistaCraps(){

		}

		public virtual void Dispose(){

		}

		private AccesoYVistaCraps(){

		}

		public static AccesoYVistaCraps ObtenerInstancia(){

			return null;
		}

		/// 
		/// <param name="param"></param>
		public void EntrarCraps(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void SalirCraps(ParametrosPedido param){

		}

	}//end AccesoYVistaCraps

}//end namespace Controlador