///////////////////////////////////////////////////////////
//  AccesoYManejoAdministrador.java
//  Implementation of the Class AccesoYManejoAdministrador
//  Generated by Enterprise Architect
//  Created on:      29-Jun-2008 07:45:36 p.m.
//  Original author: giga
///////////////////////////////////////////////////////////




using MVC.Vista;
namespace MVC.Controlador {
	public class AccesoYManejoAdministrador {

		private static AccesoYManejoAdministrador instancia;
		public AccesoYManejoAdministrador m_AccesoYManejoAdministrador;



		~AccesoYManejoAdministrador(){

		}

		public virtual void Dispose(){

		}

		private AccesoYManejoAdministrador(){

		}

		public static AccesoYManejoAdministrador ObtenerInsancia(){

			return null;
		}

		/// 
		/// <param name="param"></param>
		public void PedidoReporteRankingDeJugadores(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void PedidoReporteEstadoActual(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void PedidoReporteDetalleMovimientosPorJugador(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void EstablecerModoDirigidoTragamonedas(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void EstablecerModoDirigidoCraps(ParametrosPedido param){

		}

	}//end AccesoYManejoAdministrador

}//end namespace Controlador