///////////////////////////////////////////////////////////
//  JuegoCraps.java
//  Implementation of the Class JuegoCraps
//  Generated by Enterprise Architect
//  Created on:      29-Jun-2008 07:45:36 p.m.
//  Original author: GIGA
///////////////////////////////////////////////////////////




using MVC.Vista;
namespace MVC.Controlador {
	public class JuegoCraps {

		private static JuegoCraps instancia;
		public JuegoCraps m_JuegoCraps;



		~JuegoCraps(){

		}

		public virtual void Dispose(){

		}

		private JuegoCraps(){

		}

		public static JuegoCraps ObtenerInstancia(){

			return null;
		}

		/// 
		/// <param name="param"></param>
		public void ApostarCraps(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void TirarCraps(ParametrosPedido param){

		}

	}//end JuegoCraps

}//end namespace Controlador