///////////////////////////////////////////////////////////
//  AccesoYJuegoTragamonedas.java
//  Implementation of the Class AccesoYJuegoTragamonedas
//  Generated by Enterprise Architect
//  Created on:      29-Jun-2008 07:45:35 p.m.
//  Original author: GIGA
///////////////////////////////////////////////////////////




using MVC.Vista;
namespace MVC.Controlador {
	public class AccesoYJuegoTragamonedas {

		private static AccesoYJuegoTragamonedas instancia;
		public AccesoYJuegoTragamonedas m_AccesoYJuegoTragamonedas;



		~AccesoYJuegoTragamonedas(){

		}

		public virtual void Dispose(){

		}

		private AccesoYJuegoTragamonedas(){

		}

		public static AccesoYJuegoTragamonedas ObtenerInstancia(){

			return null;
		}

		/// 
		/// <param name="param"></param>
		public void ApostarTragamonedas(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void EntrarTragamonedas(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void SalirTragamonedas(ParametrosPedido param){

		}

		/// 
		/// <param name="param"></param>
		public void TirarTragamonedas(ParametrosPedido param){

		}

	}//end AccesoYJuegoTragamonedas

}//end namespace Controlador